const GAMES = {
  resonance: {
    title: 'RESONANCE',
    status: 'Релиз',
    version: 'V.1.7.1',
    released: '2026',
    url: 'https://dmitriromanusha1-sys.github.io/resonance/',
    genre: 'Инди · Хоррор',
    difficulty: 'Хардкор',
    description: 'Хоррор про охранника на секретном Объекте 499. Выживайте в ночные смены, следя за камерами наблюдения и управляя системами безопасности. Каждая ночь опаснее предыдущей.',
    screenshots: [
      'RESONANCE/resonance-1.png',
      'RESONANCE/resonance-2.png',
      'RESONANCE/resonance-3.png',
      'RESONANCE/resonance-4.png',
      'RESONANCE/resonance-5.png',
      'RESONANCE/resonance-6.png',
    ],
    changelog: [
      'V.1.7.1 — Исправления и оптимизация',
      'V.1.7.0 — Новый контент и уровни',
      'V.1.6.0 — Улучшен игровой процесс',
    ],
  },
  fnaf: {
    title: 'FNAF',
    status: 'Релиз',
    version: 'V.1.6.7',
    released: '2026',
    url: 'https://dmitriromanusha1-sys.github.io/fnaf-game/',
    genre: 'Инди · Хоррор',
    difficulty: 'Сложно',
    description: 'Выживите 7 ночей в роли охранника пиццерии Freddy Fazbear. Следите за камерами, закрывайте двери и экономьте энергию, пока четыре аниматроника — Freddy, Bonnie, Chica и Foxy — охотятся на вас.',
    screenshots: [
      'FNAF/fnaf-1.png',
      'FNAF/fnaf-2.png',
      'FNAF/fnaf-3.png',
      'FNAF/fnaf-4.png',
      'FNAF/fnaf-5.png',
      'FNAF/fnaf-6.png',
    ],
    changelog: [
      'V.1.6.7 — Баг-фиксы и балансировка',
      'V.1.6.0 — Новые механики',
      'V.1.5.0 — Добавлены новые персонажи',
    ],
  },
  evtn: {
    title: 'EVTN',
    status: 'Релиз',
    version: 'V.1.0.0',
    released: '2026',
    url: 'https://dmitriromanusha1-sys.github.io/evolution/',
    genre: 'Рогалик',
    difficulty: 'Средне',
    description: 'Волновой шутер с системой эволюции оружия — от лука до плазменной пушки. Выживайте в 8 волнах врагов, прокачивайте характеристики и навыки, сражайтесь с боссами. Доступны режимы Нормальный и Хардкор.',
    screenshots: [
      'EVTN/evtn-1.png',
      'EVTN/evtn-2.png',
      'EVTN/evtn-3.png',
    ],
    changelog: [
      'V.1.0.0 — Первый полный релиз',
    ],
  },
  shot: {
    title: 'Shot',
    status: 'Релиз',
    version: 'V.1.9.0',
    released: '2026',
    url: 'https://dmitriromanusha1-sys.github.io/Shot/',
    genre: 'Рогалик',
    difficulty: 'Средне',
    description: 'Киберпанк-шутер с 10 уровнями и финальным боссом. Семь видов оружия от пистолета до лазерной пушки, система прокачки арсенала, ежедневные испытания и неоновая атмосфера будущего.',
    screenshots: [
      'Shot/shot-1.png',
      'Shot/shot-2.png',
      'Shot/shot-3.png',
      'Shot/shot-4.png',
      'Shot/shot-5.png',
    ],
    changelog: [
      'V.1.9.0 — Крупное обновление контента',
      'V.1.8.0 — Новые уровни и оружие',
      'V.1.7.0 — Оптимизация производительности',
    ],
  },
  outpost: {
    title: 'Outpost_Game',
    status: 'Бета',
    version: 'V.0.4.0',
    released: '2026',
    url: 'https://dmitriromanusha1-sys.github.io/outpost-game/',
    genre: 'Рогалик',
    difficulty: 'Легко',
    description: 'Стратегическая защита деревни в реальном времени. Стройте башни и укрепления, управляйте ресурсами, прокачивайте ветки навыков. 17 карт, смена погоды и цикл день-ночь.',
    screenshots: [
      'Outpost/outpost-1.png',
      'Outpost/outpost-2.png',
      'Outpost/outpost-3.png',
      'Outpost/outpost-4.png',
      'Outpost/outpost-5.png',
    ],
    changelog: [
      'V.0.4.0 — Новые механики строительства',
      'V.0.3.0 — Добавлены враги и волны',
      'V.0.2.0 — Базовый геймплей',
    ],
  },
};
