const GAMES = {
  resonance: {
    title: 'RESONANCE',
    status: 'Релиз',
    version: 'V.1.7.1',
    released: '2026',
    url: 'https://dmitriromanusha1-sys.github.io/resonance/',
    genre: 'Инди · Хоррор',
    tags: ['#horror', '#hardcore', '#stealth'],
    difficulty: 'Хардкор',
    description: 'Хоррор про охранника на секретном Объекте 499. Выживайте в ночные смены, следя за камерами наблюдения и управляя системами безопасности. Каждая ночь опаснее предыдущей.',
    screenshots: [
      'RESONANCE/resonance-1.jpg',
      'RESONANCE/resonance-2.jpg',
      'RESONANCE/resonance-3.jpg',
      'RESONANCE/resonance-4.jpg',
      'RESONANCE/resonance-5.jpg',
      'RESONANCE/resonance-6.jpg',
    ],
    changelog: [
      'V.1.7.1 — Исправления и оптимизация',
      'V.1.7.0 — Новый контент и уровни',
      'V.1.6.0 — Улучшен игровой процесс',
    ],
  },
  fnaf: {
    title: 'FNAF',
    status: 'Релиз',
    version: 'V.1.6.7',
    released: '2026',
    url: 'https://dmitriromanusha1-sys.github.io/fnaf-game/',
    genre: 'Инди · Хоррор',
    tags: ['#horror', '#survival', '#nights'],
    difficulty: 'Сложно',
    description: 'Выживите 7 ночей в роли охранника пиццерии Freddy Fazbear. Следите за камерами, закрывайте двери и экономьте энергию, пока четыре аниматроника — Freddy, Bonnie, Chica и Foxy — охотятся на вас.',
    screenshots: [
      'FNAF/fnaf-1.jpg',
      'FNAF/fnaf-2.jpg',
      'FNAF/fnaf-3.jpg',
      'FNAF/fnaf-4.jpg',
      'FNAF/fnaf-5.jpg',
      'FNAF/fnaf-6.jpg',
    ],
    changelog: [
      'V.1.6.7 — Баг-фиксы и балансировка',
      'V.1.6.0 — Новые механики',
      'V.1.5.0 — Добавлены новые персонажи',
    ],
  },
  evtn: {
    title: 'EVTN',
    status: 'Релиз',
    version: 'V.1.0.0',
    released: '2026',
    url: 'https://dmitriromanusha1-sys.github.io/evolution/',
    genre: 'Рогалик',
    tags: ['#roguelike', '#shooter', '#evolution'],
    difficulty: 'Средне',
    description: 'Волновой шутер с системой эволюции оружия — от лука до плазменной пушки. Выживайте в 8 волнах врагов, прокачивайте характеристики и навыки, сражайтесь с боссами. Доступны режимы Нормальный и Хардкор.',
    screenshots: [
      'EVTN/evtn-1.jpg',
      'EVTN/evtn-2.jpg',
      'EVTN/evtn-3.jpg',
    ],
    changelog: [
      'V.1.0.0 — Первый полный релиз',
    ],
  },
  shot: {
    title: 'Shot',
    status: 'Релиз',
    version: 'V.1.9.0',
    released: '2026',
    url: 'https://dmitriromanusha1-sys.github.io/Shot/',
    genre: 'Рогалик',
    tags: ['#roguelike', '#cyberpunk', '#shooter'],
    difficulty: 'Средне',
    description: 'Киберпанк-шутер с 10 уровнями и финальным боссом. Семь видов оружия от пистолета до лазерной пушки, система прокачки арсенала, ежедневные испытания и неоновая атмосфера будущего.',
    screenshots: [
      'Shot/shot-1.jpg',
      'Shot/shot-2.jpg',
      'Shot/shot-3.jpg',
      'Shot/shot-4.jpg',
      'Shot/shot-5.jpg',
    ],
    changelog: [
      'V.1.9.0 — Крупное обновление контента',
      'V.1.8.0 — Новые уровни и оружие',
      'V.1.7.0 — Оптимизация производительности',
    ],
  },
  outpost: {
    title: 'Outpost_Game',
    status: 'Релиз',
    version: 'V.1.1.0',
    released: '2026',
    url: 'https://dmitriromanusha1-sys.github.io/outpost-game/',
    genre: 'Стратегия',
    tags: ['#strategy', '#defense', '#release'],
    difficulty: 'Легко',
    description: 'Стратегическая защита деревни в реальном времени. Стройте башни и укрепления, управляйте ресурсами, прокачивайте ветки навыков. 17 карт, смена погоды и цикл день-ночь.',
    screenshots: [
      'Outpost/outpost-1.jpg',
      'Outpost/outpost-2.jpg',
      'Outpost/outpost-3.jpg',
      'Outpost/outpost-4.jpg',
      'Outpost/outpost-5.jpg',
    ],
    changelog: [
      'V.1.1.0 — Анимация атаки врагов, лимит врагов против лагов, баланс сложности',
      'V.1.0.0 — Релиз: исправлены баги, добавлены метаданные и скачивание',
      'V.0.4.0 — Новые механики строительства',
      'V.0.3.0 — Добавлены враги и волны',
      'V.0.2.0 — Базовый геймплей',
    ],
  },
  oligarch: {
    title: 'Zero to Oligarch',
    status: 'Релиз',
    version: 'V.1.3.0',
    released: '2026',
    url: 'https://github.com/dmitriromanusha1-sys/zero-to-oligarch/releases/download/v1.3.0/ZeroToOligarch-v1.3.0-win64.zip',
    genre: 'Симулятор',
    tags: ['#simulator', '#economy', '#tycoon', '#release'],
    difficulty: 'Средне',
    downloadOnly: true,
    description: 'Симулятор жизни и бизнес-тайкун: путь от бомжа до олигарха. Работайте по сменам, учитесь, покупайте жильё, инвестируйте. Живая экономика (инфляция, циклы, налоги, региональные цены). Постройте бизнес-империю: портфель компаний, филиалы и франшизы, борьба за долю рынка, поглощения (M&A), IPO, R&D, антимонополия, международная экспансия. Соберите империю недвижимости: доходные объекты от комнаты до ЖК, рынок с колеблющимися ценами, ипотека, ремонт и класс объектов, простои и наёмный управляющий. 9 районов города — от Трущоб до Высшего света.',
    screenshots: [
      'OLIGARCH/oligarch-1.png',
      'OLIGARCH/oligarch-2.png',
      'OLIGARCH/oligarch-3.png',
      'OLIGARCH/oligarch-4.png',
      'OLIGARCH/oligarch-5.png',
    ],
    changelog: [
      'V.1.3.0 — Империя недвижимости: доходные объекты (от комнаты до ЖК), рынок с колеблющимся индексом цен, ипотека с риском изъятия, ремонт и класс объектов (★×3), простои/обслуживание/плохие жильцы и наёмный управляющий',
      'V.1.2.0 — Бизнес-империя: портфель компаний, филиалы/франшизы, доля рынка и конкуренты, управление (COO/CEO), поглощения (M&A), IPO, корпоративные технологии (R&D), антимонополия и кризисы, международная экспансия, вертикальная интеграция',
      'V.1.1.0 — Живая экономика: инфляция, циклы (бум/рецессия), налоги, региональные цены, ценовые шоки, экран «Финансы». Интерактивное обучение, честный ранний баланс, фиксы сохранений. Движок Godot 4.7',
      'V.1.0.0 — Полноценный релиз: смены, образование с экзаменами, сон и жильё, сезоны года, радио-тюнер, слоты сохранений, 4 сложности',
      'V.0.6.3 — Первая публичная бета-версия',
    ],
  },
  floorbyfloor: {
    title: 'Floor by Floor',
    status: 'Релиз',
    version: 'V.1.0',
    released: '2026',
    url: 'https://github.com/dmitriromanusha1-sys/floor-by-floor/releases/download/v1.0/FloorByFloor.zip',
    genre: 'Хоррор',
    tags: ['#horror', '#survival', '#release'],
    difficulty: 'Средне',
    downloadOnly: true,
    description: 'Survival-хоррор от первого лица: вы заперты в многоэтажке, заполненной зомби. Исследуйте этажи, обыскивайте квартиры, собирайте оружие и припасы, следите за голодом, жаждой и энергией, читайте записки, чтобы раскрыть, что произошло в здании. Процедурная генерация этажей, шумовая система ИИ зомби, дневник, достижения и сохранения.',
    screenshots: [
      'FLOORBYFLOOR/floorbyfloor-1.png',
      'FLOORBYFLOOR/floorbyfloor-2.png',
      'FLOORBYFLOOR/floorbyfloor-3.png',
      'FLOORBYFLOOR/floorbyfloor-4.png',
      'FLOORBYFLOOR/floorbyfloor-5.png',
      'FLOORBYFLOOR/floorbyfloor-6.png',
      'FLOORBYFLOOR/floorbyfloor-7.png',
    ],
    changelog: [
      'V.1.0 — Релиз: инвентарь, дневник, достижения, сохранения, настройки яркости/чувствительности, экранный отклик урона',
    ],
  },
};
